size: 256

generator:
    n_mlp: 8
    block_type: nat
    style_dim: 512
    lr: 0.00004
    channel_multiplier: 2
    mlp_ratio: 4
    use_checkpoint: False
    lr_mlp: 0.01
    enable_full_resolution: 8
    min_heads: 4
    qkv_bias: True
    qk_scale: null
    proj_drop: 0.
    attn_drop: 0.
    kernels: [[3],[7],[7],[7],[7],[7],[7],[7],[7]]
    dilations: [[1],[1],[1,2],[1,4],[1,8],[1,16],[1,32],[1,64],[1,128]]
    reg_every: null
    params: 0

discriminator:
    lr: 0.0002
    channel_multiplier: 2
    blur_kernel: [1, 3, 3, 1]
    sn: True
    ssd: False
    reg_every: 16
    params: 0

training:
    iter: 1000000
    batch: 8
    use_flip: True
    ttur: True
    r1: 10
    bcr: True
    bcr_fake_lambda: 10
    bcr_real_lambda: 10
    beta1: 0.0
    beta2: 0.99
    start_dim: 512
    workers: 8
    lr_decay: True
    lr_decay_start_steps: 775000
    gan_weight: 1
