defaults:
    - default_conf
    - runs: ffhq_256
    - _self_

type: train
device: cuda
latent: 4096
world_size: 1
rank: 0
local_rank: 0
distributed: True
workers: 0
save_root: ./

dataset:
    name: ffhq
    path: /data/datasets/ffhq_256

inference:
    num_images: 1
    save_path: sample_images
    batch: 1

logging:
    wandb: False
    log_img_batch: False
    print_freq: 1000
    eval_freq: 50000
    save_freq: 25000
    checkpoint_path: relative/from/save_path
    sample_path: relative/from/save_path
    reuse_samplepath: True

evaluation:
    gt_path: /data/datasets/ffhq_256/images/
    num_batches: 12500
    total_size: 50000
    batch: 4
    attn_map: True
    save_attn_map: False
    attn_map_path: attn_maps
    const_attn_seed: True

wandb:
    project_name: my_stylenat
    entity: my_wand_team
    run_name: ffhq_256_reproduce
